name: Automatic Rebase
on:
  issues:
    types: [labeled]
jobs:
  rebase:
    name: Rebase
    runs-on: ubuntu-latest
    if: github.event.label.name == 'action:rebase'
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
      - name: Automatic Rebase
        uses: cirrus-actions/rebase@1.8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: action:rebase